TITLE = ".col-12.text-center >h2"
SEARCH_BAR = "#search-input"
SORT_DROPDOWN = "#sort-select"
SEARCH_BUTTON = "[type='submit']"
PRODUCT_CONTAINER = "product-list"
ALL_PRODUCTS_CARDS = "#product-list > div"
ALL_PRODUCTS_IMAGES = "#product-list img"
ALL_PRODUCTS_TITLES = ".card-title"
ALL_PRODUCTS_PRICES = ".card-body > p:nth-of-type(2)"
ALL_PRODUCTS_STAR_RATINGS = ".card-body > p:nth-of-type(3)"
ALL_VIEW_DETAILS_BUTTONS = "[data-qa='view-product-btn']"
