# Product Detail Page Locators
PRODUCT_NAME = "[data-qa='nav-products']"
PRODUCT_PRICE = "#product-price span"
PRODUCT_DESCRIPTION = "#product-description"
PRODUCT_IMAGE = "#product-image"
AVARAGE_RATING = "#average-rating"
RATING_COUNT = "#rating-count"
RATING_STARS = ".rating-stars.mt-1"
ADD_TO_CART_BUTTON = "#add-to-cart-btn"
QUANTITY_INPUT = "[data-qa='quantity-input']"
COMMENT_INPUT = "#comment-text"
POST_COMMENT_BUTTON = "[data-qa='submit-comment-btn']"
PRODUCT_REVIEWS_CONTAINER = "#comments-container"
FIRST_COMMENT_INPUT = "[id='comments-container'] >div:nth-of-type(1) >p"
PRODUCT_REVIEW_ITEMS = ""
PRODUCT_REVIEW_AUTHOR = "#comments-container strong"
PRODUCT_REVIEW_TEXT = "#comments-container p"
PRODUCT_QUANTITY_IN_CART = "[type='number']"
REMOVE_FROM_CART_BUTTON = "[data-qa='cart-remove']"
TOAL_PRICE_IN_CART = "#cart-total"
ALL_PRICES_IN_CART = "[data-qa='cart-item-total']"
