REGISTRATION_PAGE_TITLE = ".text-center.mb-4"
USERNAME_FIELD = "#register-form > div:nth-child(1)"
EMAIL_FIELD = "#register-form > div:nth-child(2)"
PASSWORD_FIELD = "#register-form > div:nth-child(3)"
REGISTER_BUTTON = "[type='submit']"
ALREADY_HAVE_AN_ACCOUNT_LINK = ".text-center.mt-3"
